version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-template:0.0.1
    restart: unless-stopped
    tty: true
    ports:
      - "8000:6001"
    networks:
      - bridge
    working_dir: /root
    env_file: .env
#    volumes:
#      - .:/root

networks:
  bridge:
    driver: bridge
